# Generated by Django 6.0.1 on 2026-01-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_remove_resume_candidate_name_remove_resume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='actual_resume_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
