# Generated by Django 6.0.1 on 2026-01-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resume_actual_resume_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
